services:
  api:
    container_name: api
    build: .
    command: >
        sh -c "python -m src.api.main"
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db

  bot:
    container_name: bot
    build: .
    command: >
        sh -c "python -m src.bot.main"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
