services:
  api:
    container_name: api
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements/api.txt # Указываем файл с зависимостями для API
    command: >
        sh -c "
        python -m alembic upgrade head &&
        python -m src.api.main"
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      db:
        condition: service_healthy

  bot:
    container_name: bot
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements/bot.txt # Указываем файл с зависимостями для бота
    command: >
        sh -c "python -m src.bot.main"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB} # Нужно явно указать название базы данных при первом запуске, иначе она не создастся
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
